backend:
  name: git-gateway
  branch: master

logo_url: https://www.pohodovadevitka.cz/images/logo.png
media_folder: static/uploads
public_folder: /assets

collections:
  - name: blog
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Template Key"
        name: templateKey
        widget: hidden
        default: "blog-post"
      - label: "Title"
        name: title
        widget: string
      - label: "Publish Date"
        name: date
        widget: datetime
      - label: "Description"
        name: description
        widget: text
      - label: "Body"
        name: body
        widget: markdown
      - label: "Tags"
        name: tags
        widget: list
  - name: results
    label: "Ročníky"
    label_singular: "Ročník"
    folder: "src/pages/results"
    create: true
    fields:
      - label: "Template Key"
        name: templateKey,
        widget: hidden,
        default: "results-page"
      - label: "Název ročníku"
        name: title
        widget: string
      - label: "Ročník"
        name: startDate
        widget: date
      - label: "Propozice"
        name: proposition
        widget: file
      - label: "Disciplíny"
        label_singular: "Disciplína"
        name: races
        widget: list
        fields:
          - label: "Název disciplíny"
            name: name
            widget: string
          - label: "Kategorie"
            name: categories
            widget: list
            fields:
              - label: "Název kategorie"
                name: name
                widget: string
              - label: "Zkratka"
                name: abbr
                widget: string
              - label: "Pohlaví"
                name: gender
                widget: select
                default: male
                options:
                  - { label: "Muži", value: "male" }
                  - { label: "Ženy", value: "female" }
              - label: "Ročníky od"
                name: yearFrom
                widget: number
                valueType: int
                min: 1900
                max: 2100
              - label: "Ročníky do"
                name: yearTo
                widget: number
                valueType: int
                min: 1900
                max: 2100
          - label: "Výsledky"
            label_singular: "Výsledky"
            name: results
            widget: list
            fields:
              - label: "Jméno závodníka"
                name: name
                widget: string
              - label: "Kategorie"
                name: category
                widget: string
                hint: "Musí přesně odpovídat zkratece nekteré kategorie této discipíny"
              - label: "Startovní číslo"
                name: number
                widget: string
              - label: "Ročník"
                name: year
                widget: number
                valueType: int
                min: 1900
                max: 2100
              - label: "Klub"
                name: club
                widget: string
              - label: "Čas"
                name: time
                widget: string
                pattern: ["^[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}$", "Musí být platný čas v ISO formátu: hh:mm:ss.uuu"]
  - name: pages
    label: "Stránky"
    files:
      - file: "src/pages/kdo-jsme/index.md"
        label: "Kdo jsme"
        name: kdo-jsme
        fields:
          - label: "Template Key"
            name: templateKey
            widget: hidden
            default: "team-page"
          - label: "Členové"
            name: members
            widget: list
            fields:
              - label: "Jméno"
                name: name
                widget: string
              - label: "Portrét"
                name: image
                widget: image
              - label: "Sporty"
                name: sports
                widget: list
                hint: "čárkou oddělený seznam oblíbených sportů"
              - label: "Oblíbení sportovci"
                name: favorits
                widget: list
                fields:
                  - label: "Jméno"
                    name: name
                    widget: string
                  - label: "Webová adresa"
                    name: url
                    widget: string
              - label: "Popis"
                name: description
                widget: text
